title: <p align="center"> Vaibhav Kumthekar </p>
logo: /assets/img/logo.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/vaibhav-kumthekar-311b9315">LinkedIn</a> |
  <a href="https://github.com/vaibhav-nk">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
